rut=input(" Ingrese su rut: ")
nom=input(" Ingrese el nombre del alumno: ")
curso=input(" Ingrese el curso a matricularse: ")
matricula=int(25000)
mensualidad=int(30000)
resultado_anual=matricula+(mensualidad*10)

print("-----Detalle anual del matricula-----")
print(f" Nombre del alumno = {nom}")
print(f" Rut = {rut}")
print(f" Curso = {curso}")
print(f" Matricula = ${matricula}")
print(f" Mensualidad = ${mensualidad}")
print(f" Valor anual a pagar = ${resultado_anual}")